source '/REDACTED//'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.0'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

#Removing spring since it has issues in Rails 4.2 and doesn't consistently watch all config files (i.e. more headache than it's worth)
# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
# gem 'spring',        group: :development

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# To use a debugger
# gem 'byebug', group: [:development, :test]

gem 'archmage-ruby'
gem 'chronic_duration'
gem 'execjs'
gem 'haml-rails'
gem 'kaminari'
gem 'pry'
gem 'pry-nav'
gem 'pry-stack_explorer'
gem 'rdiscount'
gem 'simple_form'
gem 'mysql2'
gem 'jira-ruby', '~> 0.1.14', require: 'jira'
gem 'rails_config', '0.5.0beta1'
gem '/REDACTED/', '>= 0.2.12'
gem 'httparty'
gem 'jquery-tablesorter'
gem 'jquery-countdown-rails'
gem 'jquery-turbolinks'
gem 'clockwork'
gem 'retries'
gem '/REDACTED/'


group :development do
  gem 'awesome_print'
  gem 'wirble'
end

gem '/REDACTED/', '~> 1.0.0'
gem '/REDACTED/', '~> 1.0.0'
gem '/REDACTED/', '~> 2.0.0'
gem '/REDACTED/', '~> 1.0.0'
group :development, :test do
  gem 'rspec-rails'
  gem 'factory_girl_rails', '4.5.0'
  gem 'faker'
end

group :test do
  gem 'simplecov'
  gem 'bourne'
  gem 'database_cleaner'
  gem 'capybara'
  gem 'cucumber-rails', require: false
  gem 'guard'
  gem 'guard-cucumber'
  gem 'guard-rspec'
  gem 'terminal-notifier-guard', require: false
  gem 'webmock'
end
